=== xmontr/weblogic-monitor/weblogic-monitor-xml/src/XSD/jmxMonitor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="type.monitor.cec" xmlns:tns="type.monitor.cec" xmlns="http://www.w3.org/2001/XMLSchema">
    <complexType name="MonitorConfig">
    	<sequence>
    		<element name="counter" type="tns:Counter" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    
    <complexType name="Attribut">
    	<sequence>
    		<element name="jmxAttribut" type="string"></element>
    		<element name="description" type="string"></element>
    		<element name="name" type="string"></element>
    		<element name="keys" type="tns:CompositeValue" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	<attribute name="isComposite" type="boolean" use="optional"></attribute>
    </complexType>

    <complexType name="Counter">
    	<sequence>
    		<element name="jmxObjectName" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="jmxType" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="attribut" type="tns:Attribut"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>


    <element name="monitorConfig" type="tns:MonitorConfig"></element>

    <complexType name="CompositeValue">
    	<sequence>
    		<element name="key" type="string"></element>
    		<element name="description" type="string"></element>
    	</sequence>
    </complexType>
</schema>

=== xmontr/weblogic-monitor/weblogic-monitor-servlet/src/main/webapp/WEB-INF/configFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:monitorConfig xmlns:tns="type.monitor.cec" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="type.monitor.cec jmxMonitor.xsd ">
  <counter>
    <jmxObjectName>java.lang:type=MemoryPool,name=Eden Space</jmxObjectName>
    <attribut isComposite="true">
      <jmxAttribut>CollectionUsage</jmxAttribut>
      <description>CollectionUsage</description>
      <name>CollectionUsage</name>
      <keys>
    	  <key>used</key>
       	<description> Eden Space:used 	</description>
       </keys>    
             <keys>
    	  <key>max</key>
       	<description> Eden Space:max 	</description>
       </keys> 
    </attribut>
    <attribut >
          <jmxAttribut>CollectionUsageThreshold</jmxAttribut>
      <description>CollectionUsageThreshold</description>
      <name>CollectionUsageThreshold</name>
    </attribut >
  </counter>
</tns:monitorConfig>
